import "./globals.css";
import { dosis } from "./fonts/fonts";

export const metadata = {
  title: "Poké Berries ¡Find yours!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dosis.className} } antialiased`}>
        {children}
      </body>
    </html>
  );
}
